inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.6

  Exclude:
    - "vendor/**/*"
    - "bin/**/*"
    - "db/**/*"
    - "tmp/**/*"
    - "node_modules/**/*"
    - "lib/tasks/auto_annotate_models.rake"
  Rails:
    Enabled: true

Rails/FilePath:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Exclude:
    - "app/controllers/users/registrations_controller.rb"

Rails/HelperInstanceVariable:
  Exclude:
    - "app/helpers/notifications_helper.rb"

HashSyntax:
  EnforcedStyle: ruby19

Documentation:
  Enabled: false

################### Layout #############################

Layout/ClassStructure:
  Enabled: true

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/ExtraSpacing:
  Exclude:
    - "db/migrate/*.rb"

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Layout/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false

################### Lint #############################

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*_spec.rb"

################### Metrics #############################

Metrics/LineLength:
  Max: 160
  Exclude:
    - "db/migrate/*.rb"

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  CountComments: false
  Max: 20

#################### Style #################################

Style/AsciiComments:
  Enabled: false

Style/BlockDelimiters:
  AutoCorrect: false
  Exclude:
    - "spec/**/*_spec.rb"

Style/HashSyntax:
  Exclude:
    - "**/*.rake"
    - "Rakefile"

Style/Semicolon:
  Exclude:
    - "spec/**/*_spec.rb"

#################### RSpec #################################
RSpec/ContextWording:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false
