version: 2.0
orbs:
  ruby: circleci/ruby@0.1.2
  slack: circleci/slack@4.1.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.6-stretch-node
        environment:
          RAILS_ENV: test
          BUNDLER_VERSION: 2.1.4

      - image: circleci/mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
          MYSQL_ROOT_HOST: "%"
          TZ: "Asia/Tokyo"

    working_directory: ~/pfcdotcom
    environment:
      TZ: "Asia/Tokyo"

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: bundler install
          command: |
            gem install bundler:2.1.4

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s

      - run: yarn install
      - run: mv config/database.yml.ci config/database.yml
      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

      # - run:
      #     command: bundle exec rspec --format progress --format RspecJunitFormatter --out ~/rspec/rspec.xml

      # - run:
      #     name: run tests
      #     command: |
      #       mkdir -p /tmp/test-results
      #       TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"
      #       bundle exec rspec --format documentation \
      #                         --format RspecJunitFormatter \
      #                         --out /tmp/test-results/rspec.xml \
      #                         -- $(echo "${TEST_FILES}" | sed -e 's/\n/\\n/' -e 's/ /\ /')

      - run: mkdir ~/rspec
      - run:
          name: run tests
          command: bundle exec rspec --format progress --format RspecJunitFormatter -o ~/rspec/rspec.xml
          when: always
      - store_test_results:
          path: ~/rspec

      #     when: always
      # - store_test_results:
      #     path: ~/rspec

      # # run tests!
      # - run:
      #     name: run tests
      #     command: |
      #       mkdir /tmp/test-results
      #       TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"

      #       bundle exec rspec --format progress \
      #                       --format RspecJunitFormatter \
      #                       --out /tmp/test-results/rspec.xml \
      #                       $TEST_FILES

      # collect reports
      # - store_test_results:
      #     path: /tmp/test-results
      # - store_artifacts:
      #     path: /tmp/test-results
      #     destination: test-results

      # run rubocop
      # - run:
      #     name: run rubocop
      #     command: bundle exec rubocop

      - add_ssh_keys:
          fingerprints:
            - "da:20:23:59:3a:44:11:20:94:7e:f1:36:73:54:03:30"
      - deploy:
          name: Capistrano deploy
          command: |
            if [ "${CIRCLE_BRANCH}" != "master" ]; then
              exit 0
            fi
            bundle exec cap production deploy
