name: Deploy

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true
      - uses: miloserdow/capistrano-deploy@master
        with:
          target: production
          deploy_key: ${{ secrets.DEPLOY_ENC_KEY }}

  success_notify:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: slack notify
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: "デプロイが完了しました :bell:"
          SLACK_CHANNEL: general
          SLACK_COLOR: "#3278BD"

  failure_notify:
    if: failure()
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: slack notify
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: "デプロイに失敗しました :bell:"
          SLACK_CHANNEL: general
          SLACK_COLOR: "#FF0000"
